/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_simple_jni_NativeWorld */

#ifndef _Included_com_example_simple_jni_NativeWorld
#define _Included_com_example_simple_jni_NativeWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_simple_jni_NativeWorld
 * Method:    wayFromSwitch
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_simple_1jni_NativeWorld_wayFromSwitch
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_simple_jni_NativeWorld
 * Method:    wayFromArray
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_simple_1jni_NativeWorld_wayFromArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_simple_jni_NativeWorld
 * Method:    wayFromSwitchGlobal
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_simple_1jni_NativeWorld_wayFromSwitchGlobal
  (JNIEnv *, jobject);

/*
 * Class:     com_example_simple_jni_NativeWorld
 * Method:    wayFromArrayGlobal
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_simple_1jni_NativeWorld_wayFromArrayGlobal
  (JNIEnv *, jobject);

/*
 * Class:     com_example_simple_jni_NativeWorld
 * Method:    setGlobalId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_simple_1jni_NativeWorld_setGlobalId
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
